/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/q3IA6NvqZw0
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
export function NavigationComponent() {
  return (
    <nav className="fixed z-10 top-4 text-sm font-medium  ">
      <div className="bg-gray-200 bg-opacity-80 backdrop-blur-md px-1 py-1 rounded-[100px] inline-flex">
        <a href="/" className="bg-white rounded-[100px] px-6 py-2.5   transition-colors">Home</a>
        <a href="/profile" className="bg-transparent rounded-[100px] px-6 py-2.5   transition-colors">Profile</a>
        <a href="/contact" className="bg-transparent rounded-[100px] px-6 py-2.5   transition-colors">Contact</a>
      </div>
    </nav>
  )
}
