'use client'
import { cn } from "@/lib/utils";
import Link from "next/link";
import { usePathname } from "next/navigation";

/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/q3IA6NvqZw0
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
export function NavigationComponent() {
  const pathname = usePathname();
  const isHome = pathname === "/home";
  const isProfile = pathname === "/profile";
  const isContact = pathname === "/contact";


  return (
    <nav className="fixed z-10 my-8  ">
      <div className="bg-gray-200 bg-opacity-70 backdrop-blur-md px-1 py-1 rounded-[100px] inline-flex gap-1">
        <Link href="/home"
          className={cn(" rounded-[100px] px-6 py-2.5 transition-colors duration-700",
            isHome ? "bg-white" : "bg-transparent")}>Home</Link>
        <Link href="/profile"
          className={cn("bg-transparent rounded-[100px] px-6 py-2.5   transition-colors duration-700",
            isProfile ? "bg-white" : "bg-transparent")}>Profile</Link>
        <Link href="/contact"
          className={cn("bg-transparent rounded-[100px] px-6 py-2.5   transition-colors duration-700",
            isContact ? "bg-white" : "bg-transparent")}>Contact</Link>
      </div>
    </nav>
  )
}
