import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";


const notoSans = Noto_Sans({
  subsets: ["latin"],
  axes: ["wdth"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={notoSans.className}>{children}</body>
    </html>
  );
}
